FROM node:20.6

WORKDIR /usr/local/app

COPY package*.json ./

RUN npm install 

COPY . .

ENV PUBLIC_BACKEND_URL=http://backend:8000
ENV ORIGIN=http://localhost:3000

RUN npm run build

EXPOSE 3000

CMD ["node", "build"]