services: 

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./.env
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
   
  frontend:
    container_name: frontend
    build: ./frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend