FROM python:3.13
WORKDIR /usr/local/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./backend
EXPOSE 8000

WORKDIR /usr/local/app/backend
RUN useradd app 
USER app 

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]