name: get googleDrive Photos

on: 
    # schedule: 
    #     - cron: '0 0 * * *'

    push:
        branches:
            - main
            - gh-pages
            - gDriveSetup
    # Allow running workflow manually from the Actions tab
    workflow_dispatch: 

permissions: 
    contents: write
    id-token: write

concurrency: 
    group: "pages"
    cancel-in-progress: false

env: 
    BRANCH_NAME: keys_update--${{ github.run_id }}-${{ github.run_attempt }}
    GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}

jobs:
    Run-Python-Script: 
        outputs:
            changes: ${{ steps.git-check.outputs.changes }}

        runs-on: ubuntu-latest

        steps: 
            - name: Check out repo to runner
              uses: actions/checkout@v4
              with: 
                fetch-depth: 0
                
            - name: Configure Git
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                git checkout main
                git fetch origin
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with: 
                python-version: 3.12

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Run gDrive Script
              run: .github/scripts/fetchPhotos.py

            - name: check for changes
              id: git-check
              run: |
                if git diff --quiet; then
                  echo "No changes detected, exiting workflow successfully"
                  exit 0
                fi
                echo "changes=true" >> $GITHUB_OUTPUT

            - name: continue workflow
              if: steps.git-check.outputs.changes == 'true'
              run: echo "Changes detected, continuing workflow"

            - name: cut a branch
              if: steps.git-check.outputs.changes == 'true'
              run: |
                git checkout -b ${{ env.BRANCH_NAME }}
                git push -u origin ${{ env.BRANCH_NAME }}

            - name: stage changed files
              if: steps.git-check.outputs.changes == 'true'
              run: git add .

            - name: commit changed files
              if: steps.git-check.outputs.changes == 'true'
              run: git commit -m "replacing keys"

            - name: fetch from branch
              if: steps.git-check.outputs.changes == 'true'
              run: git fetch origin ${{ env.BRANCH_NAME }}

            - name: push code to branch
              if: steps.git-check.outputs.changes == 'true'
              run: git push origin ${{ env.BRANCH_NAME }}

            - name: generate pull request
              if: steps.git-check.outputs.changes == 'true'
              run: gh pr create -B main -H ${{ env.BRANCH_NAME }} --title "${{ env.BRANCH_NAME }}" --body "Created by GHA Workflow"
            
